# Generated by Django 5.0.1 on 2024-01-10 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_quantity',
            new_name='product_qty',
        ),
    ]
